Donor: Add referral answer tab.
stiftelsen-effekt/effekt-admin pull request #258
Opened 2022-08-18 11:54 UTC by xim

This closes issue #206

@JorgenLjones @fellmirr
![image](https://user-images.githubusercontent.com/169057/185388476-07bcfbba-6a8a-4d44-b241-84cd7ee260d3.png)

2022-08-18 12:49 UTC, fellmirr requested changes

2022-08-18 13:49 UTC, xim commented on src/store/donors/donor-page.saga.ts
> +    yield put(getDonorReferralAnswersAction.done({ params: action.payload, result: Object.values(data.content).map((r: any) => {
That gives `Property 'map' does not exist on type 'string | IReferralAnswer[]'.`

So this just one of many possible workarounds for that.

2022-08-18 13:49 UTC, xim commented on src/components/pages/donors/Donor.tsx
> +            <ReactTable
Will do.

2022-08-19 09:17 UTC, fellmirr commented on src/store/donors/donor-page.saga.ts
> +    yield put(getDonorReferralAnswersAction.done({ params: action.payload, result: Object.values(data.content).map((r: any) => {
Lets solve this a bit more generally in a separate PR as discussed :)

2022-08-19 11:24 UTC, fellmirr approved these changes

2022-08-19 11:24 UTC, merged